# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f777b7a147b73b5fa86e9cd9a396f786a706715d8b1c4a52f575da9e773c2fccf936f3769cfef72433211512d5abc3f7734925b1d3414a735796052f83e0ba3

test:
  secret_key_base: d9d12cb0bfbb47675e0b108c3600a5781b9ecdce2bf62306221f4c1a251fe5e3f0408088d577b3f9b147fa18b9f1c3e1a6bee0cd64b91dbe483d13e989c06987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
